language: csharp
solution: aws-csharp.sln
mono: none
dotnet: 2.1.302
install:
    - dotnet restore
    - nvm install 10.15.0
    - nvm use 10.15.0
    - npm install -g serverless
script:
    - ./build.sh
    - sls deploy