jobs:
    build:
        docker:
            - image: microsoft/dotnet
        steps:
            - checkout
            - run:
                name: Install dependencies
                command: dotnet restore; apt-get install node; npm install -g serverless
            - run:
                name: Build
                command: ./build.sh
            - run:
                name: Deploy
                command: sls deploy
                